#!/bin/bash

# Link Authentication Migration Tasks to Epic PAC-286
echo "🔗 Linking Tasks to Epic PAC-286: GCP Authentication Migration"
echo ""

# Add comments to each task indicating Epic relationship
echo "📝 Adding Epic relationship comments to all tasks..."

# Sprint 1 Tasks (PAC-264 to PAC-268)
echo "Adding Epic link comments to Sprint 1 tasks..."
jira add-comment --issue PAC-264 --comment "🏗️ Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 1 (Foundation & Security) - Story Points: 2"
jira add-comment --issue PAC-265 --comment "🏗️ Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 1 (Foundation & Security) - Story Points: 3"
jira add-comment --issue PAC-266 --comment "🏗️ Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 1 (Foundation & Security) - Story Points: 2"
jira add-comment --issue PAC-267 --comment "🏗️ Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 1 (Foundation & Security) - Story Points: 3"
jira add-comment --issue PAC-268 --comment "🏗️ Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 1 (Foundation & Security) - Story Points: 1"

# Sprint 2 Tasks (PAC-269 to PAC-273)
echo "Adding Epic link comments to Sprint 2 tasks..."
jira add-comment --issue PAC-269 --comment "🔄 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 2 (User Migration & RBAC) - Story Points: 2"
jira add-comment --issue PAC-270 --comment "🔄 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 2 (User Migration & RBAC) - Story Points: 5"
jira add-comment --issue PAC-271 --comment "🔄 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 2 (User Migration & RBAC) - Story Points: 5"
jira add-comment --issue PAC-272 --comment "🔄 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 2 (User Migration & RBAC) - Story Points: 3"
jira add-comment --issue PAC-273 --comment "🔄 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 2 (User Migration & RBAC) - Story Points: 2"

# Sprint 3 Tasks (PAC-274 to PAC-279)
echo "Adding Epic link comments to Sprint 3 tasks..."
jira add-comment --issue PAC-274 --comment "🔗 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 3 (Application Integration) - Story Points: 3"
jira add-comment --issue PAC-275 --comment "🔗 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 3 (Application Integration) - Story Points: 5"
jira add-comment --issue PAC-276 --comment "🔗 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 3 (Application Integration) - Story Points: 5"
jira add-comment --issue PAC-277 --comment "🔗 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 3 (Application Integration) - Story Points: 3"
jira add-comment --issue PAC-278 --comment "🔗 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 3 (Application Integration) - Story Points: 2"
jira add-comment --issue PAC-279 --comment "🔗 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 3 (Application Integration) - Story Points: 3"

# Sprint 4 Tasks (PAC-280 to PAC-285)
echo "Adding Epic link comments to Sprint 4 tasks..."
jira add-comment --issue PAC-280 --comment "🚀 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 4 (Production Deployment) - Story Points: 3"
jira add-comment --issue PAC-281 --comment "🚀 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 4 (Production Deployment) - Story Points: 3"
jira add-comment --issue PAC-282 --comment "🚀 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 4 (Production Deployment) - Story Points: 2"
jira add-comment --issue PAC-283 --comment "🚀 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 4 (Production Deployment) - Story Points: 2"
jira add-comment --issue PAC-284 --comment "🚀 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 4 (Production Deployment) - Story Points: 3"
jira add-comment --issue PAC-285 --comment "🚀 Part of Epic PAC-286: GCP Authentication Migration with GLBA Compliance - Sprint 4 (Production Deployment) - Story Points: 1"

echo ""
echo "✅ Comments added to all 22 tasks linking them to Epic PAC-286"
echo ""
echo "📋 Epic and Task Summary:"
echo "   Epic: PAC-286 - GCP Authentication Migration with GLBA Compliance"
echo "   Tasks: PAC-264 through PAC-285 (22 stories)"
echo "   Total Story Points: 62"
echo "   Timeline: 8 weeks (4 sprints)"
echo ""
echo "⚠️  Manual Steps Required in Jira UI:"
echo "1. Open Epic PAC-286 in Jira"
echo "2. For each task PAC-264 through PAC-285:"
echo "   - Edit the task"
echo "   - Set 'Epic Link' field to 'PAC-286'"
echo "   - Save the task"
echo ""
echo "📋 Task List for Manual Epic Linking:"
echo "Sprint 1 (Foundation & Security):"
echo "  • PAC-264: GCP Project Setup & Configuration (2 pts)"
echo "  • PAC-265: Identity Platform Multi-Tenant Setup (3 pts)"
echo "  • PAC-266: GLBA Compliance Configuration (2 pts)"
echo "  • PAC-267: Security Vulnerability Assessment (3 pts)"
echo "  • PAC-268: Development Environment Setup (1 pt)"
echo ""
echo "Sprint 2 (User Migration & RBAC):"
echo "  • PAC-269: User Data Analysis & Migration Strategy (2 pts)"
echo "  • PAC-270: MD5 Password Migration Implementation (5 pts)"
echo "  • PAC-271: RBAC System Design & Implementation (5 pts)"
echo "  • PAC-272: User Migration Execution (3 pts)"
echo "  • PAC-273: Migration Validation & Testing (2 pts)"
echo ""
echo "Sprint 3 (Application Integration):"
echo "  • PAC-274: Shared Authentication Library Development (3 pts)"
echo "  • PAC-275: Dashboard Application Integration (5 pts)"
echo "  • PAC-276: API Services Integration (5 pts)"
echo "  • PAC-277: Signers Application Integration (3 pts)"
echo "  • PAC-278: Client Application Integration (2 pts)"
echo "  • PAC-279: SSO Implementation & Cross-App Navigation (3 pts)"
echo ""
echo "Sprint 4 (Production Deployment):"
echo "  • PAC-280: Production Environment Preparation (3 pts)"
echo "  • PAC-281: Security Testing & Penetration Testing (3 pts)"
echo "  • PAC-282: Performance Testing & Optimization (2 pts)"
echo "  • PAC-283: User Acceptance Testing & Training (2 pts)"
echo "  • PAC-284: Production Deployment (3 pts)"
echo "  • PAC-285: Post-Deployment Monitoring & Support (1 pt)"
echo ""
echo "🎯 Alternative: Use Jira's Bulk Edit Feature"
echo "1. In Jira, go to Issues → Search for issues"
echo "2. Use JQL: project = PAC AND key >= PAC-264 AND key <= PAC-285"
echo "3. Select all 22 issues"
echo "4. Choose 'Bulk Change' → 'Edit Issues'"
echo "5. Add 'Epic Link' field and set to 'PAC-286'"
echo "6. Apply to all selected issues"